spring:
  cloud:
    stream:
      function:
        definition : paymentProcessor
      bindings:
        paymentProcessor-in-0 :   # in means consumer
          destination: order-event #Topic name
        paymentProcessor-out-0:    # ont -> means publish
          destination: payment-event  # Topic name


server:
  port: 8082