spring:
  cloud:
    stream:
      function:
        definition : orderSupplier;paymentEventConsumer
      bindings:
        orderSupplier-out-0:     # out means publish
          destination: order-event
        paymentEventConsumer-in-0 :
          destination: payment-event   # Topic name



server:
  port: 8081